<?php

namespace App\Domain\Access;

final class PermissionCatalogue
{
    public const PROTECTED_AUTHORITY_ROLE = 'director';

    /** @return list<string> */
    public static function all(): array
    {
        return [
            ...BillingPermissions::all(),
            'dashboard.view.own',
            'profile.view.own',
            'staff.view.own',
            'staff.view.branch',
            'staff.view.organisation',
            'staff.manage.organisation',
            'branches.view.branch',
            'branches.view.organisation',
            'branches.manage.organisation',
            'public_checkin_links.manage.organisation',
            'medicines.manage.organisation',
            'branch_context.switch.branch',
            'branch_context.switch.organisation',
            'access.view.organisation',
            'access.manage.organisation',
            'audit.view.organisation',
            'system_events.view.organisation',
            'patients.search.organisation',
            'patients.view.organisation',
            'patients.create.organisation',
            'patients.update.organisation',
            'patients.identifiers.manage.organisation',
            'visits.view.branch',
            'visits.create.branch',
            'visits.update.branch',
            'visits.cancel.branch',
            'queue.view.own',
            'queue.view.branch',
            'queue.enter.branch',
            'queue.call.own',
            'queue.call.branch',
            'encounters.view.own',
            'encounters.start.own',
            'encounters.update.own',
            'encounters.history.view.organisation',
            'allergies.view.own',
            'allergies.update.own',
            'allergies.review.own',
            'problems.view.own',
            'problems.update.own',
            'treatment_plans.view.own',
            'treatment_plans.create.own',
            'treatment_plans.update.own',
            'treatment_plans.send_to_dispensary.own',
            'dispensary.view.branch',
            'dispensary.start.branch',
            'dispensary.update.branch',
            'dispensary.complete.branch',
            'dispensary.return_to_doctor.branch',
            'dispensary.acknowledge_partial.own',
            'inventory.view.branch',
            'inventory.opening_balance.branch',
            'inventory.transfer.branch',
            'inventory.transfer.organisation',
            'inventory.references.manage.organisation',
            'inventory.suppliers.manage.organisation',
            'inventory.purchase_orders.create.organisation',
            'inventory.purchase_orders.approve.organisation',
            'inventory.receiving.branch',
            'inventory.stock_requests.create.branch',
            'inventory.stock_requests.approve.branch',
            'inventory.transfers.dispatch.branch',
            'inventory.transfers.receive.branch',
            'inventory.stocktake.branch',
            'inventory.adjust.branch',
            'inventory.reorder.manage.branch',
            'inventory.warehouse.organisation',
            'consultations.complete.own',
            'consultations.reopen.own',
            'services.confirm.own',
        ];
    }

    /** @return array<string, list<string>> */
    public static function roles(): array
    {
        $own = ['dashboard.view.own', 'profile.view.own', 'staff.view.own'];
        $branch = [
            ...$own,
            'staff.view.branch',
            'branches.view.branch',
            'branch_context.switch.branch',
        ];
        $organisation = [
            ...$own,
            'staff.view.organisation',
            'branches.view.organisation',
            'branch_context.switch.organisation',
        ];

        $roles = [
            'director' => [
                ...$organisation,
                'staff.manage.organisation',
                'branches.manage.organisation',
                'public_checkin_links.manage.organisation',
                'medicines.manage.organisation',
                'inventory.references.manage.organisation',
                'inventory.view.branch',
                'inventory.suppliers.manage.organisation',
                'inventory.purchase_orders.approve.organisation',
                'access.view.organisation',
                'access.manage.organisation',
                'audit.view.organisation',
                'system_events.view.organisation',
                'patients.search.organisation',
                'patients.view.organisation',
                'patients.create.organisation',
                'patients.update.organisation',
                'patients.identifiers.manage.organisation',
                'visits.view.branch',
                'visits.create.branch',
                'visits.update.branch',
                'visits.cancel.branch',
                'queue.view.branch',
                'queue.enter.branch',
                'queue.call.branch',
            ],
            'resident_doctor' => [
                ...$branch,
                'patients.search.organisation',
                'patients.view.organisation',
                'visits.view.branch',
                'queue.view.own',
                'queue.call.own',
                'encounters.view.own',
                'encounters.start.own',
                'encounters.update.own',
                'encounters.history.view.organisation',
                'allergies.view.own',
                'allergies.update.own',
                'allergies.review.own',
                'problems.view.own',
                'problems.update.own',
                'treatment_plans.view.own',
                'treatment_plans.create.own',
                'treatment_plans.update.own',
                'treatment_plans.send_to_dispensary.own',
                'dispensary.acknowledge_partial.own',
                'consultations.complete.own',
                'consultations.reopen.own',
                'services.confirm.own',
            ],
            'ca' => [
                ...$branch,
                'patients.search.organisation',
                'patients.view.organisation',
                'patients.create.organisation',
                'patients.update.organisation',
                'visits.view.branch',
                'visits.create.branch',
                'visits.update.branch',
                'visits.cancel.branch',
                'queue.view.branch',
                'queue.enter.branch',
                'dispensary.view.branch',
                'dispensary.start.branch',
                'dispensary.update.branch',
                'dispensary.complete.branch',
                'dispensary.return_to_doctor.branch',
                'inventory.view.branch',
                'inventory.transfer.branch',
                'inventory.stock_requests.create.branch',
                'inventory.transfers.receive.branch',
            ],
            'ca_supervisor' => [
                ...$branch,
                'patients.search.organisation',
                'patients.view.organisation',
                'patients.create.organisation',
                'patients.update.organisation',
                'patients.identifiers.manage.organisation',
                'visits.view.branch',
                'visits.create.branch',
                'visits.update.branch',
                'visits.cancel.branch',
                'queue.view.branch',
                'queue.enter.branch',
                'queue.call.branch',
                'dispensary.view.branch',
                'dispensary.start.branch',
                'dispensary.update.branch',
                'dispensary.complete.branch',
                'dispensary.return_to_doctor.branch',
                'inventory.view.branch',
                'inventory.opening_balance.branch',
                'inventory.transfer.branch',
                'inventory.transfer.organisation',
                'medicines.manage.organisation',
                'inventory.references.manage.organisation',
                'inventory.purchase_orders.create.organisation',
                'inventory.receiving.branch',
                'inventory.stock_requests.create.branch',
                'inventory.stock_requests.approve.branch',
                'inventory.transfers.dispatch.branch',
                'inventory.transfers.receive.branch',
                'inventory.stocktake.branch',
                'inventory.adjust.branch',
                'inventory.reorder.manage.branch',
                'inventory.warehouse.organisation',
            ],
            'panel_officer' => $organisation,
            'finance_officer' => [
                ...$organisation,
                'inventory.view.branch',
                'inventory.suppliers.manage.organisation',
                'inventory.purchase_orders.create.organisation',
            ],
            'business_development' => $organisation,
            'marketing' => $organisation,
            'hr_manager' => [
                ...$organisation,
                'staff.manage.organisation',
                'access.view.organisation',
                'audit.view.organisation',
            ],
            'technical_admin' => [
                ...$organisation,
                'staff.manage.organisation',
                'branches.manage.organisation',
                'access.view.organisation',
                'access.manage.organisation',
                'audit.view.organisation',
                'system_events.view.organisation',
            ],
        ];
        foreach (BillingPermissions::roles() as $role => $permissions) {
            $roles[$role] = [...$roles[$role], ...$permissions];
        }

        return $roles;
    }

    public static function isAdministrativeAuthority(string $permission): bool
    {
        return str_contains($permission, '.manage.');
    }
}
